import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties
import java.io.FileInputStream

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.sqldelight)
}


// ─────────────────────────────────────────────────────────────────────────────
// BuildInfo — the app's own version, available at RUNTIME.
//
// packageVersion/versionName are BUILD-time only; the in-app updater has to
// compare what is INSTALLED against what is published, so the number has to
// survive into the binary. Generated rather than hand-maintained so it can
// never disagree with the version CI actually packaged (-PappVersion).
// ─────────────────────────────────────────────────────────────────────────────
val appVersionName: String = (project.findProperty("appVersion") as String?) ?: "1.0.0"

val generateBuildInfo by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/buildinfo")
    val version = appVersionName
    outputs.dir(outDir)
    inputs.property("version", version)
    doLast {
        // Only plain values are captured here — capturing anything script-scoped
        // breaks the configuration cache ("cannot serialize Gradle script object
        // references").
        val f = outDir.get().file("com/bnm/lab/BuildInfo.kt").asFile
        f.parentFile.mkdirs()
        f.writeText(
            """
            package com.bnm.lab

            /** Generated by the `generateBuildInfo` Gradle task — do not edit. */
            object BuildInfo {
                /** The version this binary was packaged as, e.g. "1.0.0". */
                const val VERSION: String = "$version"
            }
            """.trimIndent() + "\n"
        )
    }
}

kotlin {
    // expect/actual classes (DriverFactory, ConnectivityMonitor) are still a Beta
    // Kotlin feature; this is the recommended flag to silence the Beta warning.
    compilerOptions { freeCompilerArgs.add("-Xexpect-actual-classes") }

    androidTarget {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_11) }
    }

    listOf(iosArm64(), iosSimulatorArm64()).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    jvm("desktop")

    sourceSets {
        // Generated BuildInfo.kt (app version at runtime) — see generateBuildInfo.
        commonMain { kotlin.srcDir(generateBuildInfo) }

        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.androidx.core.ktx) // FileProvider (open generated report PDFs)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.sqldelight.android.driver)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
            implementation(libs.sqldelight.native.driver)
        }
        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.ktor.client.okhttp)
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.8.0")
                implementation(libs.sqldelight.sqlite.driver)
                implementation(libs.pdfbox) // styled A4 lab-report PDFs (report/ReportPdf.desktop.kt)
                implementation("com.fazecast:jSerialComm:2.11.0") // RS-232 analyzer interfacing (instruments/)
            }
        }
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.androidx.navigation.compose)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.ktor.client.logging)
            implementation(libs.ktor.network) // raw TCP for ESC/POS network thermal printers
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.datetime)
            implementation(libs.multiplatform.settings)
            implementation("com.russhwolf:multiplatform-settings-no-arg:1.1.1")
            implementation(libs.qrose) // QR painter (UPI pay + payment links)
            implementation(compose.materialIconsExtended)
            implementation(libs.sqldelight.runtime)
            implementation(libs.sqldelight.coroutines.extensions)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

// Release signing: read from a gitignored keystore.properties (or CI env vars).
// Absent → release builds simply stay unsigned, so the build never breaks.
val keystorePropsFile = rootProject.file("keystore.properties")
val keystoreProps = Properties().apply {
    if (keystorePropsFile.exists()) FileInputStream(keystorePropsFile).use { load(it) }
}

android {
    namespace = "com.bnm.lab"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.bnm.lab"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        // Derived from the SAME -PappVersion CI passes, so an APK from a
        // release/1.1.0 build can never label itself 1.0.0. versionCode packs
        // x.y.z as x*10000 + y*100 + z (1.1.0 -> 10100), which stays
        // monotonic as long as minor/patch stay under 100.
        versionCode = appVersionName.split(".").let { p ->
            (p.getOrNull(0)?.toIntOrNull() ?: 1) * 10000 +
                (p.getOrNull(1)?.toIntOrNull() ?: 0) * 100 +
                (p.getOrNull(2)?.toIntOrNull() ?: 0)
        }
        versionName = appVersionName
    }
    packaging {
        resources { excludes += "/META-INF/{AL2.0,LGPL2.1}" }
    }
    signingConfigs {
        create("release") {
            val sf = keystoreProps.getProperty("RELEASE_STORE_FILE") ?: System.getenv("RELEASE_STORE_FILE")
            if (sf != null) {
                storeFile = rootProject.file(sf)
                storePassword = keystoreProps.getProperty("RELEASE_STORE_PASSWORD") ?: System.getenv("RELEASE_STORE_PASSWORD")
                keyAlias = keystoreProps.getProperty("RELEASE_KEY_ALIAS") ?: System.getenv("RELEASE_KEY_ALIAS")
                keyPassword = keystoreProps.getProperty("RELEASE_KEY_PASSWORD") ?: System.getenv("RELEASE_KEY_PASSWORD")
            }
        }
    }
    buildTypes {
        getByName("debug") { isMinifyEnabled = false }
        getByName("release") {
            isMinifyEnabled = false
            signingConfigs.getByName("release").storeFile?.let { if (it.exists()) signingConfig = signingConfigs.getByName("release") }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    debugImplementation(libs.compose.uiTooling)
}

// Generates the typed `AppDatabase` into com.bnm.lab.db from the .sq files
// under composeApp/src/commonMain/sqldelight/com/bnm/lab/db/.
sqldelight {
    databases {
        create("AppDatabase") {
            packageName.set("com.bnm.lab.db")
        }
    }
}

compose.resources {
    publicResClass = true
    packageOfResClass = "com.bnm.lab.resources"
}

compose.desktop {
    application {
        mainClass = "com.bnm.lab.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            // Display name of the INSTALLED app (Start menu, /Applications).
            // The published asset filenames in release.yml stay BNM Lab-* —
            // bnmapp.com links straight at those URLs.
            packageName = "BNM Lab"
            packageVersion = (project.findProperty("appVersion") as String?) ?: "1.0.0"
            // jlink trims the bundled runtime to a minimal module set — anything
            // not listed here is MISSING at runtime (dev `gradlew run` uses the
            // full JDK, so these only break in the packaged app):
            //   java.sql        → SQLDelight JDBC driver ("java/sql/DriverManager" crash)
            //   java.naming     → OkHttp/Ktor TLS internals
            //   jdk.unsupported → sun.misc.Unsafe (sqlite-jdbc / okio)
            //   java.logging    → PDFBox / commons-logging (JUL backend)
            modules("java.sql", "java.naming", "jdk.unsupported", "java.logging")
            description = "BNM Lab — offline-first diagnostic laboratory (LIMS)"
            vendor = "BNM"
            windows {
                menu = true
                shortcut = true
                menuGroup = "BNM Lab"
                perUserInstall = true
                // Fresh UUID for BNM Lab (never reuse BNMAdmin's).
                upgradeUuid = "b7e1c0a2-3f4d-4a8b-9c2e-1d6f0a5b7c93"
            }
            macOS { bundleID = "com.bnm.lab" }
            linux {
                shortcut = true
                menuGroup = "BNM Lab"
                // Debian package names cannot contain spaces or capitals, so the
                // display name above needs an explicit machine name here.
                packageName = "bnm-lab"
            }
        }
    }
}
